### ISSUE TITLE
Infineon DemoSense2Go XMC4700 programs don't work

### ISSUE THREAD

**Issue by ashwinj92** [Infineon/XMC-for-Arduino#172] opened 2021-04-21 22:40 UTC
Hi Team,

The examples for DemoSense2Go XMC4700 provided in this documentation dont seem to work: https://www.infineon.com/dgdl/Infineon-AN605_Sense2GoL_Pulse_Demo_Board-ApplicationNotes-v01_00-EN.pdf?fileId=5546d462700c0ae601708bd8d71f1440. 

Please provide an updated tutorial on how to program the XMC4700 Demo Radar base board.

Thanks

**Comment by mkiessling-ifx** [comment] 2021-04-22 06:06
Dear Ashwinj92, 

I assume you already stuck with the most simplest example, right? 

please have a look at the examples and libraries provided in the branch 
https://github.com/Infineon/XMC-for-Arduino/tree/24Ghz-radar

Best Regards
Michael

**Comment by techpaul** [comment] 2021-04-22 09:44
The problem is you have OLD version of library.

In a library folder is a file called library.properties that has an INCORRECT architecture value. The architure in this file is teh Arduino Board type support NOT processor, should really say 
~~~
architectures=xmc,arm
~~~
But this is sufficient (as in current release)
~~~
architectures=arm
~~~

Current version of library has this correct.

I suggest you update the Boards support form Arduino IDE

Tools -> Board....... -> Board Manager

(See installation notes)

**Comment by ashwinj92** [comment] 2021-04-27 03:12
Thank you for the replies, I have updated the board libraries to have the latest version of the library installed on the Arduino IDE as well. I'm trying to extract raw signals (I and Q for further processing) the serial monitor does not show any data at the specified baud rate. 

https://github.com/Infineon/XMC-for-Arduino/tree/24Ghz-radar and have used this documentation to the dot. And Also using the correct COM port aswell.

I get the following warning log when I compile the sketch. Any solutions would help.

WARNING: library BGT24LTR11-Pulsed-Doppler-Radar claims to run on cortex-m4 architecture(s) and may be incompatible with your current board which runs on arm architecture(s)

**Comment by techpaul** [comment] 2021-04-27 11:03
The radar branch is separate from the main release, I have tried some of the standard release V1.5.0 and EXAMPLES for Sense2Go and had NO compiler warnings for boards XMC 4400 Platform2Go or DEMO Radar BB XMC4700. 

The wrning you are seeing is an Arduino IDE compiler warning based on board setting and library.properties file in the libraries tree, having checked both main release and 24GHz Radar branch I cannot see any errors in those files.

Some examples do NOT work for ANY board, you must have the correct confifuration for board (Tools -> Board....)

Important questions

1/ What version of Arduino IDE do you hve
2/ How did you install the 24GHz branch
3/ What EXACT name of boards or board set do you have
4/ What is  your Arduino IDE board setting
5/ Which examples have you tried using

To prove you are setup on correct COM port compiling and getting output try compiling and uploading the example

Device Control XMC -> DieTemperatureMeasurement
or
Device Control XMC -> StackMemoryMeasurement

These will output data onto serial port and prove you are getting correct compilation for that board when output works

**Comment by techpaul** [comment] 2021-07-19 15:44
Items have moved to separate branch and projects by looks of things so closing

**Closed by techpaul** 2021-07-19 15:44 UTC

**Comment by tinymanta** [comment] 2022-09-26 09:30
@techpaul any updates on this topic?

**Comment by techpaul** [comment] 2022-09-26 10:14
Check the 2,4 GHz branch and see if Infineon have any further answers.  I am just a contibutor.
